version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: claude-slack-postgres
    environment:
      POSTGRES_DB: claude_slack
      POSTGRES_USER: claude_bot
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - claude-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U claude_bot -d claude_slack"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  claude-network:
    driver: bridge